### ISSUE TITLE
Purpose ?

### ISSUE THREAD

**Issue by melMass** [amb/sbsar-builder#2]
Hello,

I'm not sure to understand the point of this tool, can you explain the purpose of baking textures to sbsar ?

Thanks

**Comment by amb** [comment]
It's easier to manage and integrates better with my personal pipeline. Your mileage may vary.

**Comment by melMass** [comment]
Thanks but can you explain any usage you have of this technique?
I'm maybe missing something but I don't understand why you would want to bake textures to sbar.

**Comment by amb** [comment]
It becomes a Substance that I can drag & drop to places like Substance Designer/Painter or Unity3D, or my Substances collection.
